/**
 * @module heatcalc/interaction-controller
 * @owner heat
 * @depends grid model, excel interaction, table columns, normal table interaction,
 *   resize, page selection effects
 * @does-not electrical, InsulationLayersTable, formulas, query/draft save lifecycle
 *
 * HEAT2: grid / excel / selection interaction boundary for Heat workspace.
 * Page model keeps orchestration (data, editor, bulk, toolbar, route chrome).
 */
import { useHeatCalcTableColumns } from '@/hooks/useHeatCalcTableColumns';
import {
  useHeatCalcExcelInteractionModel,
} from '@/pages/heatcalc/useHeatCalcExcelInteractionModel';
import { useHeatCalcGridModel } from '@/pages/heatcalc/useHeatCalcGridModel';
import { useHeatCalcNormalTableInteractionModel } from '@/pages/heatcalc/useHeatCalcNormalTableInteractionModel';
import { useHeatCalcPageEffectsModel } from '@/pages/heatcalc/useHeatCalcPageEffectsModel';
import { useHeatCalcResizeModel } from '@/pages/heatcalc/useHeatCalcResizeModel';

export type {
  HeatCalcExcelInteractionState,
  HeatCalcInteractionWorkspaceSlice,
  HeatCalcInteractionTableSlice,
  HeatCalcInteractionEditorSlice,
  HeatCalcInteractionFocusSlice,
  HeatCalcInteractionResizeSlice,
  UseHeatCalcInteractionControllerArgs,
} from '@/pages/heatcalc/heatCalcInteractionControllerTypes';
import type { UseHeatCalcInteractionControllerArgs } from '@/pages/heatcalc/heatCalcInteractionControllerTypes';

/** Composes grid/excel/normal interaction, resize, and selection lifecycle effects. */
export function useHeatCalcInteractionController(
  args: UseHeatCalcInteractionControllerArgs,
) {
  const { table, excelInteractionState, workspace, editor, focus, resize, notifyInfo } = args;
  const {
    activeObjectScope,
    activeTableColumnScope,
    activeTableObjectType,
    activeTablePage,
    changeNormalTablePage,
    cleanHiddenColumnState,
    isAllObjectScope,
    loadNextNormalPage,
    pruneSelectedRows,
    resetColumnFilter,
    selectObjectScope,
    selectedRowKeys,
    setColumnFilter,
  } = table;
  const {
    activeExcelCellPosition,
    activeInlineCell,
    appendExcelLocalRows,
    columnRenderers,
    commitInlineCell,
    currentTableViewActive,
    dirtyDraftRowCount,
    draftRowsById,
    editableExcelColumnKeys,
    effectiveActiveTableViewState,
    enumOptionsByColumn,
    excelLocalRows,
    excelModeEnabled,
    excelRowIds,
    fieldCapabilityByKey,
    filteredTableCount,
    formPlacement,
    isSavableDraftRow,
    normalGlideEnabled,
    objectQueryFetching,
    objectQueryResult,
    selectedExcelRows,
    setActiveInlineCell,
    setDraftRowsById,
    setExcelLocalRows,
    sourceColumnMetas,
    tableCellEditingEnabled,
    visibleSourceIndexById,
    visibleTableColumnKeys,
    visibleTableObjects,
    visibleTableRows,
  } = workspace;
  const {
    clearLastSavedObject,
    lastSavedObject,
    selectedRowId,
    syncWizardWithRecord,
    wizardBaseObject,
    wizardFormObject,
  } = editor;
  const {
    pendingTableFocusObject,
    setPendingTableFocusObject,
    setTableEditingMode,
    tableEditingMode,
  } = focus;
  const {
    applySideFormWidthPct,
    fieldInputSettings,
    persistTableColumnSettings,
    persistTableViewOnly,
    sideWorkspaceRef,
    tableColumnSettingsRef,
    tableFindabilityAvailable,
    tableViewSettingsRef,
    updateTableColumnSettingsDraft,
  } = resize;

  const {
    handleGlideColumnResize,
    handleGlideColumnResizeEnd,
    startColumnResize,
    startSideFormMouseResize,
    startSideFormResize,
  } = useHeatCalcResizeModel({
    activeTableColumnScope,
    applySideFormWidthPct,
    formPlacement,
    persistTableColumnSettings,
    persistTableViewOnly,
    sideWorkspaceRef,
    tableColumnSettingsRef,
    tableViewSettingsRef,
    updateTableColumnSettingsDraft,
  });

  const {
    selectedRowErrorMessages,
    excelCellDisplayValue,
    glideGridColumns,
    getGlideGridCellState,
    getNormalGlideGridCellState,
  } = useHeatCalcGridModel({
    activeTableObjectType,
    sourceColumnMetas,
    fieldCapabilityByKey,
    enumOptionsByColumn,
    columnRenderers,
    draftRowsById,
    editableExcelColumnKeys,
    excelModeEnabled,
    fieldInputSettings,
    isAllObjectScope,
    isSavableDraftRow,
    tableFindabilityEnabled: tableFindabilityAvailable,
    tableCellEditingEnabled,
    visibleTableRows,
    visibleSourceIndexById,
    wizardBaseObject,
    wizardFormObject,
  });

  const {
    excelContextMenu,
    selectedExcelPosition,
    clearExcelSelectionState,
    selectExcelCellByPosition,
    setExcelRangeSelection,
    selectAllExcelCells,
    beginExcelCellSelection,
    extendExcelCellSelection,
    beginExcelRowSelection,
    extendExcelRowSelection,
    beginExcelColumnSelection,
    extendExcelColumnSelection,
    openExcelCellContextMenu,
    openExcelRowContextMenu,
    openExcelRecordContextMenu,
    closeExcelContextMenu,
    copyExcelSelection,
    clearExcelSelection,
    cutExcelSelection,
    pasteExcelFromClipboard,
    addExcelRowsBelowSelection,
    resetSelectedExcelRows,
    startInlineCellEdit,
  } = useHeatCalcExcelInteractionModel({
    ...excelInteractionState,
    activeExcelCellPosition,
    appendExcelLocalRows,
    draftRowsById,
    editableExcelColumnKeys,
    excelCellDisplayValue,
    excelLocalRows,
    excelModeEnabled,
    excelRowIds,
    selectedExcelRows,
    selectedRowId,
    setActiveInlineCell,
    setDraftRowsById,
    setExcelLocalRows,
    sourceColumnMetas,
    syncWizardWithRecord,
    tableCellEditingEnabled,
    visibleTableObjects,
  });

  useHeatCalcPageEffectsModel({
    activeObjectScope,
    activeTableObjectType,
    clearExcelSelectionState,
    clearLastSavedObject,
    cleanHiddenColumnState,
    currentTableViewActive,
    dirtyDraftRowCount,
    isAllObjectScope,
    lastSavedObject,
    pendingTableFocusObject,
    pruneSelectedRows,
    selectObjectScope,
    setPendingTableFocusObject,
    setTableEditingMode,
    tableCellEditingEnabled,
    tableEditingMode,
    visibleTableColumnKeys,
    visibleTableObjects,
    notifyInfo,
  });

  const { tableColumns, tableScrollX, tableScrollY } = useHeatCalcTableColumns({
    activeTableColumnScope,
    activeTableObjectType,
    activeTableViewState: effectiveActiveTableViewState,
    activeInlineCell,
    activeExcelCellPosition,
    beginExcelCellSelection,
    beginExcelColumnSelection,
    beginExcelRowSelection,
    buildTableColumns: excelModeEnabled,
    columnRenderers,
    commitInlineCell,
    draftRowsById,
    enumOptionsByColumn,
    excelCellDisplayValue,
    editableExcelColumnKeys,
    excelModeEnabled,
    excelRowIds,
    excelSelectionRange: excelInteractionState.excelSelectionRange,
    extendExcelCellSelection,
    extendExcelColumnSelection,
    extendExcelRowSelection,
    fieldCapabilityByKey,
    fieldInputSettings,
    formPlacement,
    isAllObjectScope,
    isSavableDraftRow,
    openExcelCellContextMenu,
    openExcelRowContextMenu,
    resetColumnFilter,
    selectAllExcelCells,
    selectExcelCellByPosition,
    selectedExcelPosition,
    setActiveInlineCell,
    setColumnFilter,
    sourceColumnMetas,
    startColumnResize,
    startInlineCellEdit,
    tableFindabilityEnabled: tableFindabilityAvailable,
    tableCellEditingEnabled,
    visibleTableObjectsLength: visibleTableObjects.length,
    visibleTableRows,
  });

  const {
    handleNormalLoadMore,
    handleNormalTablePageChange,
    normalInfiniteLoading,
    normalTablePagination,
    tableRowClassName,
  } = useHeatCalcNormalTableInteractionModel({
    activeTablePage,
    changeNormalTablePage,
    columnRenderers,
    draftRowsById,
    excelModeEnabled,
    filteredTableCount,
    isAllObjectScope,
    isSavableDraftRow,
    loadNextNormalPage,
    normalGlideEnabled,
    objectQueryFetching,
    objectQueryResult,
    selectedRowId,
    selectedRowKeys,
    sourceColumnMetas,
    visibleTableObjectsLength: visibleTableObjects.length,
    visibleTableRows,
  });

  return {
    handleGlideColumnResize,
    handleGlideColumnResizeEnd,
    startSideFormMouseResize,
    startSideFormResize,
    selectedRowErrorMessages,
    glideGridColumns,
    getGlideGridCellState,
    getNormalGlideGridCellState,
    excelContextMenu,
    selectedExcelPosition,
    clearExcelSelectionState,
    setExcelRangeSelection,
    openExcelRecordContextMenu,
    closeExcelContextMenu,
    copyExcelSelection,
    clearExcelSelection,
    cutExcelSelection,
    pasteExcelFromClipboard,
    addExcelRowsBelowSelection,
    resetSelectedExcelRows,
    startInlineCellEdit,
    tableColumns,
    tableScrollX,
    tableScrollY,
    handleNormalLoadMore,
    handleNormalTablePageChange,
    normalInfiniteLoading,
    normalTablePagination,
    tableRowClassName,
  };
}
