import type { BackendEndpointMapping } from '../registry/types';

export const TLT_BACKEND_ENDPOINTS: Record<string, BackendEndpointMapping> = {
  adminFormulaCheckPipe: {
    id: 'admin_formula_check_pipe',
    method: 'POST',
    endpoint: '/api/v1/admin/formula-check',
    auth: 'admin',
    formulaType: 'pipe',
    resultPath: 'total_heat_loss',
    requestShape: '{ formula_type: "pipe", params: PipeHeatLossParams }',
    notes: ['Use testCase.metadata.backendFormulaType="pipe" with BackendApiRunner.'],
  },
  adminFormulaCheckTank: {
    id: 'admin_formula_check_tank',
    method: 'POST',
    endpoint: '/api/v1/admin/formula-check',
    auth: 'admin',
    formulaType: 'tank',
    resultPath: 'total_heat_loss',
    requestShape: '{ formula_type: "tank", params: TankHeatLossParams }',
    notes: ['Use testCase.metadata.backendFormulaType="tank" with BackendApiRunner.'],
  },
  adminFormulaCheckSelfRegulating: {
    id: 'admin_formula_check_self_regulating',
    method: 'POST',
    endpoint: '/api/v1/admin/formula-check',
    auth: 'admin',
    formulaType: 'electrical',
    resultPath: 'total_power',
    requestShape: '{ formula_type: "electrical", params: SelfRegulatingParams }',
    notes: ['Checks direct TLT self-regulating cable calculation.'],
  },
  adminFormulaCheckSelfRegulatingTt: {
    id: 'admin_formula_check_self_regulating_tt',
    method: 'POST',
    endpoint: '/api/v1/admin/formula-check',
    auth: 'admin',
    formulaType: 'electrical_tt',
    resultPath: 'total_power',
    requestShape: '{ formula_type: "electrical_tt", params: SelfRegulatingTTParams }',
    notes: ['Checks TTН/TTВ/TTХ self-regulating cable calculation.'],
  },
  adminFormulaCheckResistiveSingle: {
    id: 'admin_formula_check_resistive_single',
    method: 'POST',
    endpoint: '/api/v1/admin/formula-check',
    auth: 'admin',
    formulaType: 'resistive_single',
    resultPath: 'total_power',
    requestShape: '{ formula_type: "resistive_single", params: ResistiveSingleCoreParams }',
    notes: ['Checks TT R1 single-core resistive cable calculation.'],
  },
  adminFormulaCheckResistiveThree: {
    id: 'admin_formula_check_resistive_three',
    method: 'POST',
    endpoint: '/api/v1/admin/formula-check',
    auth: 'admin',
    formulaType: 'resistive_three',
    resultPath: 'total_power',
    requestShape: '{ formula_type: "resistive_three", params: ResistiveThreeCoreParams }',
    notes: ['Checks TT R3 three-core resistive cable calculation.'],
  },
  adminFormulaCheckTankCableGeometry: {
    id: 'admin_formula_check_tank_cable_geometry',
    method: 'POST',
    endpoint: '/api/v1/admin/formula-check',
    auth: 'admin',
    formulaType: 'tank_cable_geometry',
    resultPath: 'cable_length',
    requestShape: '{ formula_type: "tank_cable_geometry", params: TankCableGeometryCheckParams }',
    notes: ['Can be compared against independent AlgorithmOracle tlt_tank_cable_length.'],
  },
  heatLossCalculation: {
    id: 'calc_heat_loss',
    method: 'POST',
    endpoint: '/api/v1/calc/heat-loss',
    auth: 'guest',
    resultPath: 'result.total_heat_loss',
    requestShape: '{ object_type: "pipe" | "tank", data: PipeHeatLossParams | TankHeatLossParams }',
    notes: ['Production user-facing heat-loss endpoint; requires app auth context.'],
  },
  electricalCalculation: {
    id: 'calc_electrical',
    method: 'POST',
    endpoint: '/api/v1/calc/electrical',
    auth: 'guest',
    resultPath: 'result.total_power',
    requestShape: 'ElectricalRequest',
    notes: ['Production user-facing electrical calculation endpoint.'],
  },
  electricalBatchCalculation: {
    id: 'calc_electrical_batch',
    method: 'POST',
    endpoint: '/api/v1/calc/electrical/batch',
    auth: 'guest',
    requestShape: 'query params: project_id, cable_source, cable_type, variant_number, overrides',
    notes: ['Project-level flow endpoint; assert DB invariants after this runner.'],
  },
};

export function getTltBackendEndpointMapping(id: string): BackendEndpointMapping | undefined {
  return TLT_BACKEND_ENDPOINTS[id];
}
