"""API contracts for named electrical variants (ER)."""

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

ElectricalSystemType = Literal["self_regulating", "resistive"]
ElectricalAssignmentState = Literal["unassigned", "ready", "unsupported", "stale", "error"]
ElectricalSpecificationState = Literal["not_generated", "generated", "stale"]


class ElectricalReadinessIssue(BaseModel):
    """A stable diagnostic; object-level issues need not block initialization."""

    code: str
    message: str
    object_id: UUID | None = None
    details: dict[str, Any] = Field(default_factory=dict)


class ElectricalReadinessResponse(BaseModel):
    """Eligibility of the ER container plus diagnostics for its individual parts."""

    project_id: UUID
    ready: bool
    total_objects: int
    ready_objects: int
    issues: list[ElectricalReadinessIssue] = Field(default_factory=list)


class ElectricalVariantCreateRequest(BaseModel):
    """Create an empty ER; an omitted name is generated by the service."""

    name: str | None = None


class ElectricalVariantCopyRequest(BaseModel):
    """Deep-copy an ER graph; specification is deliberately excluded."""

    name: str | None = None


class ElectricalVariantRenameRequest(BaseModel):
    name: str


class ElectricalVariantResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    project_id: UUID
    name: str
    sort_order: int
    is_active: bool
    copied_from_id: UUID | None = None
    specification_state: ElectricalSpecificationState = "not_generated"
    created_at: datetime
    updated_at: datetime


class ElectricalVariantInitializeResponse(BaseModel):
    project_id: UUID
    created: bool
    assignments_created: int
    variant: ElectricalVariantResponse


class ElectricalVariantDeleteResponse(BaseModel):
    project_id: UUID
    deleted_variant_id: UUID
    active_variant_id: UUID


class ElectricalVariantErrorResponse(BaseModel):
    """Shape used in ``HTTPException.detail`` for stable client handling."""

    code: str
    message: str
    issues: list[ElectricalReadinessIssue] = Field(default_factory=list)
